version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=development
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/brahmakaal
      - JWT_SECRET_KEY=dev-secret-key
      - EMAIL_ENABLED=true
      - SMTP_HOST=smtp.zoho.in
      - SMTP_PORT=465
      - SMTP_USER=aham@brah.ma
      - SMTP_PASS=6whrzKc*@brahma
      - WEBHOOK_ENABLED=true
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=brahmakaal
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
